[project]
name = "projet-cardprofiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "a-oirgari", email = "abdrahmanghali1998@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "imbalanced-learn>=0.14.2",
    "joblib>=1.6.0",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "streamlit>=1.64.0",
]

[project.scripts]
projet-cardprofiler = "projet_cardprofiler:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.4",
]
